name: game_socket
description: Socket library for creating real-time multiplayer games. Based on TCP, with the ability to send messages over UDP (planned).
version: 0.0.1
homepage: 'https://github.com/QiXi/game_socket'

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  uuid: ^3.0.4
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0