name: game_socket
description: Socket library for creating real-time multiplayer games.
version: 0.0.0
homepage: 'https://github.com/QiXi/game_socket'

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  uuid: ^3.0.4
  meta: ^1.4.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0